name: Sodarcloud

on:
  push:
    branches:
      - workflow

env:
  MIRROR_URL: "git@github.com:AETHER-ENGINE/SONARCLOUD-TEST.git"

jobs:
  push_to_mirror:
    name: Push to Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Target Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          branches: |
            ansible
            workflow
