- name: Base
  hosts: all
  roles:
    - base
  tags: base
  vars:
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

- name: Docker
  hosts: all
  roles:
    - docker
  tags: docker

- name: Docker Swarm
  hosts: all
  roles: 
    - docker_swarm
  tags: docker_swarm